server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/some_db
    username: some_user
    password: some_password
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.PostgreSQL
    show-sql: true
    open-in-view: false